### ISSUE TITLE
build failure at compile time for ghc 7.8

### ISSUE THREAD

**Issue by cartazio** [fpco/safe-decimal#2]
it seems that currently the code doesn't correctly support ghc 7.8

the associated error is here https://matrix.hackage.haskell.org/#/package/safe-decimal/0.1.0.0/ghc-7.8.4@1556240707

```
Building library for safe-decimal-0.1.0.0..
[1 of 2] Compiling Numeric.Decimal.Internal ( src/Numeric/Decimal/Internal.hs, /tmp/matrix-worker/1556241082/dist-newstyle/build/x86_64-linux/ghc-7.8.4/safe-decimal-0.1.0.0/build/Numeric/Decimal/Internal.o )

src/Numeric/Decimal/Internal.hs:640:10:
    Not in scope: ‘uncons’
    Perhaps you meant ‘union’ (imported from Data.List)

src/Numeric/Decimal/Internal.hs:661:52:
    Not in scope: ‘displayException’

src/Numeric/Decimal/Internal.hs:670:19:
    Not in scope: ‘uncons’
    Perhaps you meant ‘union’ (imported from Data.List)
<<ghc: 425758760 bytes, 201 GCs, 10064885/26707192 avg/max bytes residency (8 samples), 75M in use, 0.00 INIT (0.00 elapsed), 0.13 MUT (0.13 elapsed), 0.22 GC (0.22 elapsed) :ghc>>

```

to better test support https://github.com/haskell-CI/haskell-ci 
if you dont want to support ghc 7.8, please set a lower bound  on base of >= 4.8

**Comment by lehins** [comment]
Thanks @cartazio

**Comment by cartazio** [comment]
glad i can help!

a few extra things:
i'm told that setting `pvp: true` in a stack yaml makes it easier to make sure the generated cabal file maps exactly to the configurations you intend to support. (apparently its not on by default due to historical reasons and stuff)
