### ISSUE TITLE
Wrong behaviour in RoundHalfUp

### ISSUE THREAD

**Issue by gusbicalho** [fpco/safe-decimal#3]
Current behavior:
```haskell
ghci> v = wrapDecimal (-125001) :: Decimal RoundHalfUp 5 Integer
ghci> roundDecimal v :: Decimal RoundHalfUp 1 Integer
-1.2
```

Expected behavior:
```haskell
ghci> v = wrapDecimal (-125001) :: Decimal RoundHalfUp 5 Integer
ghci> roundDecimal v :: Decimal RoundHalfUp 1 Integer
-1.3
```

RoundHalfUp should round _down_ in this case, because the remainder is not _exactly_ half, it's 0.5001. The current implementation is checking only the leftmost digit of the remainder.

**Comment by gusbicalho** [comment]
I'm working on a PR to fix this and add an implementation of RoundHalfDown and RoundHalfEven. However, this behaviour change breaks the generative tests (it seems the test oracle fns incorporate the same mistake), so I'll have to change them too.

**Comment by lehins** [comment]
`-1.2` is up from `-1.25`, while `-1.3` is down from `-1.25`. You are describing behavior of `RoundHalfDown`  behavior

**Comment by lehins** [comment]
Here is an example from [wikipedia](https://en.wikipedia.org/wiki/Rounding#Round_half_up): 
> For example, by this rule the value 23.5 gets rounded to 24, but −23.5 gets rounded to −23.

**Comment by lehins** [comment]
Looking forward to PRs with implementation of `RoundHalfDown` and `RoundHalfEven`.
There are already partially implemented test for `RoundHalfEven`:
https://github.com/fpco/safe-decimal/blob/b425e3d643d2f804df3a40edd5892ec6701b4da7/tests/Numeric/DecimalSpec.hs#L417-L420

**Comment by lehins** [comment]
@gusbicalho Anyhow, current behavior is the correct one, if you still belive it is not please provide some reference and examples and we'll talk about a proper fix. For now closing as invalid

**Comment by lehins** [comment]
@gusbicalho Sorry, I was dealing with multiple issues at the same time. I see what you mean now and closing this issue was wrong. I am gonna wait for your fix and investigate this issue a bit more myself

**Comment by lehins** [comment]
Just in case, for my own sanity check:
```python
>>> Decimal('-1.25000).quantize(Decimal('.1'), rounding=ROUND_HALF_DOWN)
Decimal('-1.2')
>>> Decimal('-1.25001').quantize(Decimal('.1'), rounding=ROUND_HALF_DOWN)
Decimal('-1.3')
```
```python
>>> Decimal('-1.25001').quantize(Decimal('.1'), rounding=ROUND_HALF_UP)
Decimal('-1.3')
>>> Decimal('-1.25000').quantize(Decimal('.1'), rounding=ROUND_HALF_UP)
Decimal('-1.3')
```
An now I am more confused

**Comment by lehins** [comment]
I see now, Wikipedia and Python are using different definitions of round-half-up:

* Python: 
> `ROUND_HALF_UP` (to nearest with ties going away from zero).
* Wikipedia: 
> The following tie-breaking rule, called round half up (or round half towards positive infinity),

~I guess we should implement what other languages are doing, especially considering that Wikipedia doesn't have a reference for that statement~

**Comment by gusbicalho** [comment]
Actually, the main point here is that current code is handling `-0,5001` as a tie, but it should not.

**Comment by lehins** [comment]
Scratch that. We should have those separate `RoundHalfUp` and `RoundHalfFromZero`.

I got that, it should be fixed, I just git confused there for a second with terminology:

> Actually, the main point here is that current code is handling -0,5001 as a tie, but it should not.

**Comment by gusbicalho** [comment]
`-1.25001` should be rounded to `-1.3` for all `RoundHalf` algorithms, because in fact the nearest number is `-1.3`, there is no tie here.

**Comment by gusbicalho** [comment]
> We should have those separate RoundHalfUp and RoundHalfFromZero.

Agreed 👍
